spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/debts_manager
    username: niaznazipov
    password: g9h8nfta17ror
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${client_id}
            client-secret: ${client_secret}